"""empty message

Revision ID: 07ac91b5df38
Revises: 
Create Date: 2018-03-11 00:55:45.133029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ac91b5df38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crawl_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('companyId', sa.String(length=50), server_default='', nullable=True),
    sa.Column('score', sa.String(length=50), server_default='', nullable=True),
    sa.Column('positionId', sa.String(length=50), server_default='', nullable=True),
    sa.Column('positionName', sa.String(length=120), server_default='', nullable=True),
    sa.Column('createTime', sa.String(length=50), server_default='', nullable=True),
    sa.Column('positionAdvantage', sa.Text(), server_default='', nullable=True),
    sa.Column('salary', sa.String(length=50), server_default='', nullable=True),
    sa.Column('approve', sa.String(length=50), server_default='', nullable=True),
    sa.Column('workYear', sa.String(length=50), server_default='', nullable=True),
    sa.Column('education', sa.String(length=50), server_default='', nullable=True),
    sa.Column('city', sa.String(length=50), server_default='', nullable=True),
    sa.Column('companyLogo', sa.String(length=120), server_default='', nullable=True),
    sa.Column('jobNature', sa.String(length=50), server_default='', nullable=True),
    sa.Column('industryField', sa.String(length=50), server_default='', nullable=True),
    sa.Column('companyShortName', sa.String(length=120), server_default='', nullable=True),
    sa.Column('financeStage', sa.String(length=50), server_default='', nullable=True),
    sa.Column('companyLabelList', sa.String(length=120), server_default='', nullable=True),
    sa.Column('publisherId', sa.String(length=50), server_default='', nullable=True),
    sa.Column('district', sa.String(length=50), server_default='', nullable=True),
    sa.Column('companySize', sa.String(length=50), server_default='', nullable=True),
    sa.Column('positionLables', sa.String(length=120), server_default='', nullable=True),
    sa.Column('industryLables', sa.String(length=120), server_default='', nullable=True),
    sa.Column('businessZones', sa.String(length=120), server_default='', nullable=True),
    sa.Column('formatCreateTime', sa.String(length=50), server_default='', nullable=True),
    sa.Column('longitude', sa.String(length=50), server_default='', nullable=True),
    sa.Column('latitude', sa.String(length=50), server_default='', nullable=True),
    sa.Column('companyFullName', sa.String(length=120), server_default='', nullable=True),
    sa.Column('adWord', sa.String(length=50), server_default='', nullable=True),
    sa.Column('hitags', sa.String(length=120), server_default='', nullable=True),
    sa.Column('resumeProcessRate', sa.String(length=50), server_default='', nullable=True),
    sa.Column('resumeProcessDay', sa.String(length=50), server_default='', nullable=True),
    sa.Column('imState', sa.String(length=50), server_default='', nullable=True),
    sa.Column('lastLogin', sa.String(length=50), server_default='', nullable=True),
    sa.Column('explain', sa.String(length=50), server_default='', nullable=True),
    sa.Column('plus', sa.String(length=50), server_default='', nullable=True),
    sa.Column('pcShow', sa.String(length=50), server_default='', nullable=True),
    sa.Column('appShow', sa.String(length=50), server_default='', nullable=True),
    sa.Column('deliver', sa.String(length=50), server_default='', nullable=True),
    sa.Column('gradeDescription', sa.String(length=50), server_default='', nullable=True),
    sa.Column('promotionScoreExplain', sa.String(length=50), server_default='', nullable=True),
    sa.Column('firstType', sa.String(length=50), server_default='', nullable=True),
    sa.Column('secondType', sa.String(length=50), server_default='', nullable=True),
    sa.Column('isSchoolJob', sa.String(length=50), server_default='', nullable=True),
    sa.Column('subwayline', sa.String(length=50), server_default='', nullable=True),
    sa.Column('stationname', sa.String(length=50), server_default='', nullable=True),
    sa.Column('linestaion', sa.Text(), server_default='', nullable=True),
    sa.Column('job_type', sa.String(length=50), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_jobs_crawl_time'), 'jobs', ['crawl_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_crawl_time'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
