"""empty message

Revision ID: 0d9f17700db9
Revises: 241f2e6bb526
Create Date: 2018-03-12 23:12:41.991483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9f17700db9'
down_revision = '241f2e6bb526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zljobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crawl_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('positionName', sa.String(length=120), server_default='', nullable=True),
    sa.Column('companyFullName', sa.String(length=120), server_default='', nullable=True),
    sa.Column('companyLabelList', sa.String(length=120), server_default='', nullable=True),
    sa.Column('salary', sa.String(length=50), server_default='', nullable=True),
    sa.Column('city', sa.String(length=50), server_default='', nullable=True),
    sa.Column('createTime', sa.String(length=50), server_default='', nullable=True),
    sa.Column('jobNature', sa.String(length=50), server_default='', nullable=True),
    sa.Column('workYear', sa.String(length=50), server_default='', nullable=True),
    sa.Column('education', sa.String(length=50), server_default='', nullable=True),
    sa.Column('positionCount', sa.String(length=50), server_default='', nullable=True),
    sa.Column('firstType', sa.String(length=50), server_default='', nullable=True),
    sa.Column('job_type', sa.String(length=50), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_zljobs_crawl_time'), 'zljobs', ['crawl_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zljobs_crawl_time'), table_name='zljobs')
    op.drop_table('zljobs')
    # ### end Alembic commands ###
