"""empty message

Revision ID: 19e88709e3e9
Revises: 
Create Date: 2018-03-31 23:27:35.571753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e88709e3e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'crawllogs', ['id'])
    op.add_column('jobs', sa.Column('avg_salary', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_avg_salary'), 'jobs', ['avg_salary'], unique=False)
    op.create_index(op.f('ix_jobs_positionName'), 'jobs', ['positionName'], unique=False)
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index(op.f('ix_jobs_positionName'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_avg_salary'), table_name='jobs')
    op.drop_column('jobs', 'avg_salary')
    op.drop_constraint(None, 'crawllogs', type_='unique')
    # ### end Alembic commands ###
