"""empty message

Revision ID: 1c8e843f1ae7
Revises: 30d285e0cad0
Create Date: 2018-03-31 19:50:16.204682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8e843f1ae7'
down_revision = '30d285e0cad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'crawllogs', ['id'])
    op.create_index(op.f('ix_jobs_salary'), 'jobs', ['salary'], unique=False)
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index(op.f('ix_jobs_salary'), table_name='jobs')
    op.drop_constraint(None, 'crawllogs', type_='unique')
    # ### end Alembic commands ###
