"""empty message

Revision ID: 241f2e6bb526
Revises: 07ac91b5df38
Create Date: 2018-03-12 22:58:37.253938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241f2e6bb526'
down_revision = '07ac91b5df38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jobs', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    # ### end Alembic commands ###
