"""empty message

Revision ID: 39860893439f
Revises: 1c8e843f1ae7
Create Date: 2018-03-31 20:06:03.843625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39860893439f'
down_revision = '1c8e843f1ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('time_sort', sa.String(length=50), server_default='2018-03-31', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'time_sort')
    # ### end Alembic commands ###
