"""empty message

Revision ID: 57b29d2f4c43
Revises: 0d9f17700db9
Create Date: 2018-03-12 23:33:13.381744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b29d2f4c43'
down_revision = '0d9f17700db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zljobs', sa.Column('url', sa.Text(), server_default='', nullable=True))
    op.create_unique_constraint(None, 'zljobs', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zljobs', type_='unique')
    op.drop_column('zljobs', 'url')
    # ### end Alembic commands ###
