"""empty message

Revision ID: 77f10a04a49f
Revises: 83bd323d96a6
Create Date: 2018-04-16 22:53:32.985496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f10a04a49f'
down_revision = '83bd323d96a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles_users', ['id'])
    op.add_column('users', sa.Column('password', sa.String(length=100), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'roles_users', type_='unique')
    # ### end Alembic commands ###
