"""empty message

Revision ID: 82daaa40f60c
Revises: f4847f6101f4
Create Date: 2018-03-31 21:20:53.138824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82daaa40f60c'
down_revision = 'f4847f6101f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('avg_salary', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_avg_salary'), 'jobs', ['avg_salary'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_avg_salary'), table_name='jobs')
    op.drop_column('jobs', 'avg_salary')
    # ### end Alembic commands ###
