"""empty message

Revision ID: 83bd323d96a6
Revises: 39abde0a79ce
Create Date: 2018-04-16 22:08:39.763773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bd323d96a6'
down_revision = '39abde0a79ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_roles_users_create_time'), 'roles_users', ['create_time'], unique=False)
    op.create_index(op.f('ix_roles_users_update_time'), 'roles_users', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_users_update_time'), table_name='roles_users')
    op.drop_index(op.f('ix_roles_users_create_time'), table_name='roles_users')
    op.drop_table('roles_users')
    # ### end Alembic commands ###
