"""empty message

Revision ID: 88a52fe85ae5
Revises: 77f10a04a49f
Create Date: 2018-04-16 22:57:40.823990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88a52fe85ae5'
down_revision = '77f10a04a49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='roles_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='roles_users_pkey'),
    sa.UniqueConstraint('id', name='roles_users_id_key')
    )
    # ### end Alembic commands ###
