"""empty message

Revision ID: e3b8ac109a67
Revises: 
Create Date: 2018-04-15 21:09:52.140774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b8ac109a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_cities_create_time'), 'cities', ['create_time'], unique=False)
    op.add_column('crawllogs', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_crawllogs_create_time'), 'crawllogs', ['create_time'], unique=False)
    op.add_column('jobs', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_jobs_create_time'), 'jobs', ['create_time'], unique=False)
    op.add_column('jobtypes', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_jobtypes_create_time'), 'jobtypes', ['create_time'], unique=False)
    op.add_column('messages', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_messages_create_time'), 'messages', ['create_time'], unique=False)
    op.add_column('roles', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_roles_create_time'), 'roles', ['create_time'], unique=False)
    op.add_column('users', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_users_create_time'), 'users', ['create_time'], unique=False)
    op.add_column('zljobs', sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_zljobs_create_time'), 'zljobs', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zljobs_create_time'), table_name='zljobs')
    op.drop_column('zljobs', 'create_time')
    op.drop_index(op.f('ix_users_create_time'), table_name='users')
    op.drop_column('users', 'create_time')
    op.drop_index(op.f('ix_roles_create_time'), table_name='roles')
    op.drop_column('roles', 'create_time')
    op.drop_index(op.f('ix_messages_create_time'), table_name='messages')
    op.drop_column('messages', 'create_time')
    op.drop_index(op.f('ix_jobtypes_create_time'), table_name='jobtypes')
    op.drop_column('jobtypes', 'create_time')
    op.drop_index(op.f('ix_jobs_create_time'), table_name='jobs')
    op.drop_column('jobs', 'create_time')
    op.drop_index(op.f('ix_crawllogs_create_time'), table_name='crawllogs')
    op.drop_column('crawllogs', 'create_time')
    op.drop_index(op.f('ix_cities_create_time'), table_name='cities')
    op.drop_column('cities', 'create_time')
    # ### end Alembic commands ###
