"""empty message

Revision ID: e546a64e08aa
Revises: 39860893439f
Create Date: 2018-03-31 20:07:58.006854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e546a64e08aa'
down_revision = '39860893439f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_time_sort'), 'jobs', ['time_sort'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_time_sort'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    # ### end Alembic commands ###
