"""empty message

Revision ID: f4847f6101f4
Revises: e546a64e08aa
Create Date: 2018-03-31 20:47:58.690236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4847f6101f4'
down_revision = 'e546a64e08aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_positionName'), 'jobs', ['positionName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_positionName'), table_name='jobs')
    # ### end Alembic commands ###
