from .company_route import company
from .data_route import data
from .datalog_route import datalog
from .index_route import aj
from .jobtype_route import jobtype
from .message_route import message
from .trend_route import trend
from .auth_route import auth
from .recommend_route import recommend